"use strict";

module.exports = {
	EMAIL_VERIFICATION_OTP: 'email_verification',
	PASS_RESET_OTP: 'password_reset',
	DAYS: {
		MONDAY: 'monday',
		TUESDAY: 'tuesday',
		WEDNESDAY: 'wednesday',
		THURSDAY: 'thursday',
		FRIDAY: 'friday',
		SATURDAY: 'saturday',
		SUNDAY: 'sunday',
	},
	ROLES: {
		ADMIN: 'ADMIN',
		GYM_OWNER: 'GYM.OWNER',
		COACH_OWNER: 'COACH.OWNER',
		COACH_HEAD: 'COACH.HEAD',
		COACH: 'COACH',
		PARENT_OWNER: 'PARENT.OWNER',
		PARENT: 'PARENT',
		CHILD: 'CHILD',
		INDIVIDUAL_OWNER: 'INDIVIDUAL.OWNER',
		INDIVIDUAL: 'INDIVIDUAL',
	},
	OWNER_ROLES: [
		'GYM.OWNER',
		'COACH.OWNER',
		'PARENT.OWNER',
		'INDIVIDUAL.OWNER',
	],
	USER_ASSOCIATIONS: {
		PARENT_CHILD: 'PARENT_CHILD',
		ORGANIZATION_USER: 'ORGANIZATION_USER',
		GYM_COACH: 'GYM_COACH',
	},
	PERMISSIONS: {
		ACCOUNT_MANAGE: 'ACCOUNT.MANAGE',
		ACTIVITY_MANAGE: 'ACTIVITY.MANAGE',
		ACTIVITY_APPROVE: 'ACTIVITY.APPROVE',
		ACTIVITY_VIEW: 'ACTIVITY.VIEW',
		USER_INVITE: 'USER.INVITE',
		TARGET_MANAGE: 'TARGET.MANAGE',
		SUBACCOUNT_MANAGE: 'SUBACCOUNT.MANAGE',
	}
};
