"use strict";

module.exports = {
	EMAIL_VERIFICATION_OTP: 'email_verification',
	PASS_RESET_OTP: 'password_reset',
	DAYS: {
		MONDAY: 'monday',
		TUESDAY: 'tuesday',
		WEDNESDAY: 'wednesday',
		THURSDAY: 'thursday',
		FRIDAY: 'friday',
		SATURDAY: 'saturday',
		SUNDAY: 'sunday',
	},
	ROLES: {
		ADMIN: 'ADMIN',
		GYM_OWNER: 'GYM.OWNER',
		COACH_OWNER: 'COACH.OWNER',
		COACH_HEAD: 'COACH.HEAD',
		COACH: 'COACH',
		PARENT_OWNER: 'PARENT.OWNER',
		PARENT: 'PARENT',
		CHILD: 'CHILD',
		INDIVIDUAL_OWNER: 'INDIVIDUAL.OWNER',
		INDIVIDUAL: 'INDIVIDUAL',
	},
	USER_ASSOCIATIONS: {
		PARENT_CHILD: 'PARENT_CHILD',
		ORGANIZATION_USER: 'ORGANIZATION_USER',
		GYM_COACH: 'GYM_COACH',
	},
	PERMISSIONS: {
		ACCOUNT_MANAGEMENT: 'ACCOUNT_MANAGEMENT',
		ACTIVITY_MANAGEMENT: 'ACTIVITY_MANAGEMENT',
		ACTIVITY_APPROVAL: 'ACTIVITY_APPROVAL',
		INVITE_USERS: 'INVITE_USERS',
		LEVEL_MANAGEMENT: 'LEVEL_MANAGEMENT',
	}
};
